# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_download_strategy"
class BowrainCli < Formula
  desc "Bowrain CLI — manage localization projects, sync with Bowrain Server"
  homepage "https://github.com/gokapi/gokapi"
  version "0.28.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.4/bowrain-cli_0.28.4_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "597640fa66a674cafd1b64837fb52bd8e8d3e5d584ec96fda5c88e67b08fb428"

      define_method(:install) do
        bin.install "bowrain"
        bin.install_symlink bin/"bowrain" => "brain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.4/bowrain-cli_0.28.4_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "19c2a585ed820958d2fd9f4ec797f5747759f8699801c3f4e916c111bcdaced6"

      define_method(:install) do
        bin.install "bowrain"
        bin.install_symlink bin/"bowrain" => "brain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.4/bowrain-cli_0.28.4_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "502d44fb11cc35a753858325364106372bde988b6105cc8cabe106a1f0fe46fd"
      define_method(:install) do
        bin.install "bowrain"
        bin.install_symlink bin/"bowrain" => "brain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.4/bowrain-cli_0.28.4_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "85f4c45231b44582d72e9926eb91efb18ca002da443ff105359de8c4d5ca5f0c"
      define_method(:install) do
        bin.install "bowrain"
        bin.install_symlink bin/"bowrain" => "brain"
      end
    end
  end

  test do
    system "#{bin}/bowrain", "version"
    system "#{bin}/brain", "version"
  end
end
