# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_download_strategy"
class BowrainCli < Formula
  desc "Bowrain CLI — manage localization projects, sync with Bowrain Server"
  homepage "https://github.com/neokapi/neokapi"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neokapi/neokapi/releases/download/v0.2.0/bowrain-cli_0.2.0_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8d6ab91cf34c450a719913b9d1d582b84f1576c9e3e1f310cbd8765320539554"

      define_method(:install) do
        bin.install "bowrain"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neokapi/neokapi/releases/download/v0.2.0/bowrain-cli_0.2.0_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "3595c74a6f138424d0b22a3bd6a0bf51687ece4d77788bf37f4794ef3b2be74f"

      define_method(:install) do
        bin.install "bowrain"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neokapi/neokapi/releases/download/v0.2.0/bowrain-cli_0.2.0_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6cdf5ca70eaf95fb8a6756a38018494f606c5506cf72409024db5aebc4114926"
      define_method(:install) do
        bin.install "bowrain"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neokapi/neokapi/releases/download/v0.2.0/bowrain-cli_0.2.0_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "fe102589f0b94d1c6a1a56940fd30f4a7168313124402d4ba22aab18361b74f2"
      define_method(:install) do
        bin.install "bowrain"
      end
    end
  end

  test do
    system "#{bin}/bowrain", "version"
  end
end
