# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_download_strategy"
class KapiCli < Formula
  desc "AI-native localization framework — format-aware parsing, concurrent pipelines, and pluggable tools"
  homepage "https://github.com/neokapi/neokapi"
  version "1.0.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neokapi/neokapi/releases/download/v1.0.8/kapi_1.0.8_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "721750b44709f80a940ad527a6041eec095a27b0475d2bd04a7165be4edf7dcf"

      define_method(:install) do
        bin.install "kapi"
        bin.install_symlink bin/"kapi" => "kgrep"
        bin.install_symlink bin/"kapi" => "ksed"
        bin.install_symlink bin/"kapi" => "kcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neokapi/neokapi/releases/download/v1.0.8/kapi_1.0.8_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6d871a69324389a0a5c207625f99e6106b17f47bd5194cc2c0b25e1e13d3c668"

      define_method(:install) do
        bin.install "kapi"
        bin.install_symlink bin/"kapi" => "kgrep"
        bin.install_symlink bin/"kapi" => "ksed"
        bin.install_symlink bin/"kapi" => "kcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neokapi/neokapi/releases/download/v1.0.8/kapi_1.0.8_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "aa246a0128f7716eb50eca717638d228605c18a95a9212bcc97f7e7f75d03ac1"
      define_method(:install) do
        bin.install "kapi"
        bin.install_symlink bin/"kapi" => "kgrep"
        bin.install_symlink bin/"kapi" => "ksed"
        bin.install_symlink bin/"kapi" => "kcat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neokapi/neokapi/releases/download/v1.0.8/kapi_1.0.8_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "533d1b3180420dd40e6085b5c01ecaa747b9407c6c0ccbab08ec3773eb0bddb5"
      define_method(:install) do
        bin.install "kapi"
        bin.install_symlink bin/"kapi" => "kgrep"
        bin.install_symlink bin/"kapi" => "ksed"
        bin.install_symlink bin/"kapi" => "kcat"
      end
    end
  end

  test do
    system "#{bin}/kapi", "version"
    assert_match "grep", shell_output("#{bin}/kgrep --help 2>&1")
  end
end
