# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_download_strategy"
class Kapi < Formula
  desc "AI-native localization framework — format-aware parsing, concurrent pipelines, and pluggable tools"
  homepage "https://github.com/gokapi/gokapi"
  version "0.28.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.2/kapi_0.28.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "23b4d6e9aec0c6a6a76e90316d76a62dfe78ab9b4714d54e614bb0289dfbad19"

      define_method(:install) do
        bin.install "kapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.2/kapi_0.28.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "a984fbac6afc0cc9b54cf91f54042d006bbec7893037f4d440950e55c7455122"

      define_method(:install) do
        bin.install "kapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.2/kapi_0.28.2_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "bf3c3e56bc5b880c2b33148931fea42a21dfe8af5c0b8abdc12f365470672d70"
      define_method(:install) do
        bin.install "kapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.2/kapi_0.28.2_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "de6af96361bc0f917f07e2bdadb628b6069520b633e49c1a05e7eceada0df41e"
      define_method(:install) do
        bin.install "kapi"
      end
    end
  end

  test do
    system "#{bin}/kapi", "version"
  end
end
