# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_download_strategy"
class Kapi < Formula
  desc "AI-native localization framework — format-aware parsing, concurrent pipelines, and pluggable tools"
  homepage "https://github.com/gokapi/gokapi"
  version "0.28.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.1/kapi_0.28.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "284b155ab35600d7b62db39251ec6b2970e23f7fc0feb1ff211ac767f2ed7eac"

      define_method(:install) do
        bin.install "kapi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.1/kapi_0.28.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e1418d810de776947a58e8f34b2b2c84258916756e7360704adf2d7b59e1ccbf"

      define_method(:install) do
        bin.install "kapi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.1/kapi_0.28.1_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "2cd2585b340d45a559dbe73a89e924596cdb2bdae999bffbbdebcaf76dae4f1e"
      define_method(:install) do
        bin.install "kapi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gokapi/gokapi/releases/download/v0.28.1/kapi_0.28.1_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f12123400befd719905e4edb8a6c05ca7d703100f16b6887c8598e4736ae7791"
      define_method(:install) do
        bin.install "kapi"
      end
    end
  end

  test do
    system "#{bin}/kapi", "version"
  end
end
