# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_download_strategy"
class KapiCli < Formula
  desc "AI-native localization framework — format-aware parsing, concurrent pipelines, and pluggable tools"
  homepage "https://github.com/neokapi/neokapi"
  version "1.0.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/neokapi/neokapi/releases/download/v1.0.9/kapi_1.0.9_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "723cd69a25477782c85df8d8466ce6ec759a9c7442345b06132657711f10aad7"

      define_method(:install) do
        bin.install "kapi"
        bin.install_symlink bin/"kapi" => "kgrep"
        bin.install_symlink bin/"kapi" => "ksed"
        bin.install_symlink bin/"kapi" => "kcat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/neokapi/neokapi/releases/download/v1.0.9/kapi_1.0.9_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "00cdc38f62aec28a90ee1da247e9c76adf7642c112ec542f8eb65f1cb7f50f9a"

      define_method(:install) do
        bin.install "kapi"
        bin.install_symlink bin/"kapi" => "kgrep"
        bin.install_symlink bin/"kapi" => "ksed"
        bin.install_symlink bin/"kapi" => "kcat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/neokapi/neokapi/releases/download/v1.0.9/kapi_1.0.9_linux_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c4daf2a1a7648177753ac03ae115f6a3e9dbb01e2c21d3d8fda099c668a90f76"
      define_method(:install) do
        bin.install "kapi"
        bin.install_symlink bin/"kapi" => "kgrep"
        bin.install_symlink bin/"kapi" => "ksed"
        bin.install_symlink bin/"kapi" => "kcat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/neokapi/neokapi/releases/download/v1.0.9/kapi_1.0.9_linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "c14e921c1735ac477176986034666770ee6e79db473a5b2cbe84f2bbbd7bb5f7"
      define_method(:install) do
        bin.install "kapi"
        bin.install_symlink bin/"kapi" => "kgrep"
        bin.install_symlink bin/"kapi" => "ksed"
        bin.install_symlink bin/"kapi" => "kcat"
      end
    end
  end

  test do
    system "#{bin}/kapi", "version"
    assert_match "grep", shell_output("#{bin}/kgrep --help 2>&1")
  end
end
