# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapi" do
  name "kapi"
  desc "AI-native localization framework — format-aware parsing, concurrent pipelines, and pluggable tools"
  homepage "https://github.com/gokapi/gokapi"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapi"

  on_macos do
    on_intel do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_darwin_amd64.tar.gz"
      sha256 "c12b84383d1581967b57433118650cb206effe297ee23500ac8d4252f98b3a16"
    end
    on_arm do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_darwin_arm64.tar.gz"
      sha256 "8c1a1f7c449bc599fa862f3158b094a4027124d4d6a3f284ebf181c5373627ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_linux_amd64.tar.gz"
      sha256 "8f5a512ac43b966282074e59bbc378d015b56a2c575418b885bec9ba3bb1521b"
    end
    on_arm do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_linux_arm64.tar.gz"
      sha256 "557294559b657ba59de2950d2b1581e35be26fc4ace49c73d55aab8dfb8c633d"
    end
  end

  # No zap stanza required
end
