# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapi" do
  name "kapi"
  desc "AI-native localization framework — format-aware parsing, concurrent pipelines, and pluggable tools"
  homepage "https://github.com/gokapi/gokapi"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapi"

  on_macos do
    on_intel do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_darwin_amd64.tar.gz"
      sha256 "c81bc2525bc7a8c9d0a34b0b21b87ee961b7a3252c237ca09ce74ab970b4a1b0"
    end
    on_arm do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_darwin_arm64.tar.gz"
      sha256 "7d8c390480825aacd0a63aec4494e70a613a9f90bc1abd17079836784c1560c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_linux_amd64.tar.gz"
      sha256 "166c348b2b8d6b576866f2a9b5c36f733f29c9382b33a37d6bb89e3b7f38cb07"
    end
    on_arm do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_linux_arm64.tar.gz"
      sha256 "92670c2c4605d3f0913e01cd9fd75f24d2b1e3279ef8153635a9e4b4e3395f31"
    end
  end

  # No zap stanza required
end
