# This file was generated by GoReleaser. DO NOT EDIT.
cask "kapi" do
  name "kapi"
  desc "AI-native localization framework — format-aware parsing, concurrent pipelines, and pluggable tools"
  homepage "https://github.com/gokapi/gokapi"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kapi"

  on_macos do
    on_intel do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_darwin_amd64.tar.gz"
      sha256 "45889e7d8757ec3c41d7da474abdbb29cf76f1057c628d00a0254209a660120b"
    end
    on_arm do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_darwin_arm64.tar.gz"
      sha256 "36837560f8f8eca8d074f5c71364a8f6244c039b3294661c4108a8ecb5fa9008"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_linux_amd64.tar.gz"
      sha256 "e4d626e388d9ea9e2d0d062855ee2899144b175763566b754f42d5a811efca34"
    end
    on_arm do
      url "https://github.com/gokapi/gokapi/releases/download/v#{version}/kapi_#{version}_linux_arm64.tar.gz"
      sha256 "76fcc10aef2be1cccef0990730b81b6a8681d1eb4960d2b2853244227cc7ef36"
    end
  end

  # No zap stanza required
end
